name: FastAPI CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: [self-hosted, linux, x64]
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        pip3 install -r requirements.txt
    - name: Run Tests
      run: |
        python3.10 -m src.main
