name: FastAPI CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    strategy:
      max-parallel: 4
    steps:
    - name: Delete old task
      run: |
        ls
        pm2 list
        pm2 stop boomPJ
    - name: Git pull
      run: |
        git pull
    - name: Start PM2
      run: |
        cd /home/gm/actions-runner/_work/warehouses-database/warehouses-database
        ls
        
    - name: Run Tests
      run: |
        pm2 restart boomPJ
