name: FastAPI CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    strategy:
      max-parallel: 4
    steps:
    - name: Delete old task
      run: |
        pm2 list
        pm2 delete boomPJ
    - uses: actions/checkout@v2
    - name: Start PM2
      run: |
        cd /home/gm/actions-runner/_work/warehouses-database/warehouses-database
        pm2 start '/usr/local/bin/python3.10 -u -m src.main' --name boomPJ
        pm2 save
    - name: Run Tests
      run: |
        pm2 restart boomPJ
